serviceportlist: [52032, 52018]
port: 52035
shellpath: /app/sysmgmt/res/
mdns:
  name: conthing-lpr
  port: 42424
microservicelist:
  - name: lpr
    type: status
    url: http://localhost:52032/api/v1/status
    led: /dev/led-pwm3
  - name: lpr
    type: ping
    url: http://localhost:52032/api/v1/ping
    led: /dev/led-pwm1
  - name: exportmqtt
    type: status
    url: http://localhost:52018/api/v1/status
    led: /dev/led-pwm2
  - name: exportmqtt
    type: ping
    url: http://localhost:52018/api/v1/ping
    led: /dev/led-pwm1
  - name: zigbee
      type: mesh
      url: http://localhost:52032/api/v1/mesh
      led: /dev/led-pwm3