controlled:
  urlforwwwled: 
    - "http://localhost:52018/api/v1/status"
  urlforlinkled: 
    - "http://localhost:52032/api/v1/status"
http:
  port: 52035
mdns:
  enable: true
  name: conthing-lpr
  port: 42424
microservicelist:
  - name: lpr
    port: 52032
    enablehealth: true
  - name: exportmqtt
    port: 52018
    enablehealth: true
recovery:
  contains: "lpr"
  command: "/app/zap/lpr/lpr"
  parameter:
    - "-c"
    - "/app/zap/lpr/config.yaml"
  environment:
    - "LD_LIBRARY_PATH=/app/zap/lpr"
  outputfile: "/app/log/conthing-lpr.log"
db:
  location: "/app/data/"
  dbname: "sysmgmt"
   
