controlled:
  urlforwwwled: {"http://localhost:52018/api/v1/status"}
  urlforlinkled: {"http://localhost:52032/api/v1/status"}
port: 52035
shellpath: /app/sysmgmt/res/
mdns:
  name: conthing-lpr
  port: 42424
microservicelist:
  - name: lpr
    port: 52032
    enablehealth: true
  - name: exportmqtt
    port: 52018
    enablehealth: true
