controlled:
  urlforwwwled: 
    - "http://localhost:52032/api/v1/www"
  urlforlinkled: 
    - "http://localhost:52032/api/v1/link"
http:
  port: 52035
mdns:
  enable: true
  name: lpr
  port: 80
microservicelist:
  - name: lpr
    port: 52032
    enablehealth: true
recovery:
  contains: "(.*)lpr"
  command: "bash"
  parameter:
    - "-c"
    - "/app/scripts/appstart.sh"
db:
  location: "/app/data/"
  dbname: "lpr"

